# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrkq < Formula
  desc "Task management CLI for agent/human collaboration"
  homepage "https://github.com/lherron/wrkq"
  version "0.0.1"
  license "MIT"

  depends_on "sqlite" => :recommended
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lherron/wrkq/releases/download/v0.0.1/wrkq_0.0.1_macOS_x86_64.tar.gz"
    sha256 "cc30b97b855eb4010870dd022d042fee64a2d5752515313c746f86fb42bbda0a"

    def install
      bin.install "wrkq"
      bin.install "wrkqadm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lherron/wrkq/releases/download/v0.0.1/wrkq_0.0.1_macOS_arm64.tar.gz"
    sha256 "82de751bb02c7fc279199a2f288418988d5cf8e9660597b3e4835b52e2a2ec92"

    def install
      bin.install "wrkq"
      bin.install "wrkqadm"
    end
  end

  test do
    system "#{bin}/wrkq", "--version"
    system "#{bin}/wrkqadm", "--version"
  end
end
