# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrkq < Formula
  desc "Task management CLI for agent/human collaboration"
  homepage "https://github.com/lherron/wrkq"
  version "0.0.1"
  license "MIT"

  depends_on "sqlite" => :recommended
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lherron/wrkq/releases/download/v0.0.1/wrkq_0.0.1_macOS_x86_64.tar.gz"
    sha256 "8519cbf8aebc5615f0d4dbfeb8dfed0d8b0e33678b13ac3d810e8b4d75594672"

    def install
      bin.install "wrkq"
      bin.install "wrkqadm"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lherron/wrkq/releases/download/v0.0.1/wrkq_0.0.1_macOS_arm64.tar.gz"
    sha256 "0c0de565e870312daa14784dcd04ed3020ccb55db2405aeb37577cde7a59311b"

    def install
      bin.install "wrkq"
      bin.install "wrkqadm"
    end
  end

  test do
    system "#{bin}/wrkq", "--version"
    system "#{bin}/wrkqadm", "--version"
  end
end
